### ISSUE TITLE
Unexpected Error - Logging in

### ISSUE THREAD

**Issue by jakestmart** [watkins-matt/home-assistant-google-keep-sync#28]
Hi,

Core 2024.6.1
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0
Google Keep Sync: 0.9.8

Using the MASTER TOKEN generated from the docker. 
Used Google Password / App Password.

I have re-installed, restarted etc several times. However still receiving "Unexpected Error" in the login screen.

Log:
_________________________________________________________
This error originated from a custom integration.

Logger: custom_components.google_keep_sync.config_flow
Source: custom_components/google_keep_sync/config_flow.py:233
integration: Google Keep Sync (documentation)
First occurred: 1:09:20 PM (4 occurrences)
Last logged: 1:18:42 PM

Unexpected exception: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/google_keep_sync/config_flow.py", line 233, in handle_user_input
    await self.validate_input(self.hass, user_input)
  File "/config/custom_components/google_keep_sync/config_flow.py", line 222, in validate_input
    success = await self.api.authenticate()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_keep_sync/api.py", line 113, in authenticate
    if not await self.async_login_with_saved_token():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_keep_sync/api.py", line 78, in async_login_with_saved_token
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gkeepapi/__init__.py", line 730, in resume
    auth.load(email, master_token, device_id)
  File "/usr/local/lib/python3.12/site-packages/gkeepapi/__init__.py", line 81, in load
    self.refresh()
  File "/usr/local/lib/python3.12/site-packages/gkeepapi/__init__.py", line 151, in refresh
    res = gpsoauth.perform_oauth(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpsoauth/__init__.py", line 204, in perform_oauth
    return _perform_auth_request(data, proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpsoauth/__init__.py", line 98, in _perform_auth_request
    res = session.post(AUTH_URL, data=data, verify=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

**Comment by watkins-matt** [comment]
Looking into it. Seems like it started to occur after updating to Home Assistant 2024.6.1.

**Comment by Madj42** [comment]
Getting the same thing here too.  If I can rest something, let me know.

**Comment by Tierney11290** [comment]
Same issue here. Let me know what I can provide to assist, if anything.

**Comment by FragMenthor** [comment]
This integration was one of my most seeked ones, and finally got it to work, somehow, with the master token, but now I face the same as above, any ideas? Also upgraded to core 2024.06.1, and this issue appeared, no lists on HA...

**Comment by watkins-matt** [comment]
Okay, so it looks like this is an issue specific to Home Assistant 2024.6.1 and does not occur in 2024.6.0.

There is a pull request fix open for gpsoauth here: https://github.com/simon-weber/gpsoauth/pull/67

Once that pull request is merged I can update the dependency and this issue should no longer occur. This doesn't appear to be something I can fix directly without that update to gpsoauth or a fix in Home Asisstant itself.

As a temporary workaround, you can downgrade to 2024.6.0 from 2024.6.1. You would need to SSH in to Home Assistant, and then run 
```bash
ha core update --version 2024.6.0
```
which will downgrade to the prior version. Note that you can also install the "Terminal & SSH" and use the web interface to paste that command in. It will take a bit of time to downgrade after running the command.

Related issues: https://github.com/leikoilja/ha-google-home/issues/876, https://github.com/simon-weber/gpsoauth/issues/57#

**Comment by jakestmart** [comment]
Thanks for the idea and the detailed support

**Comment by watkins-matt** [comment]
Fixed in the latest release https://github.com/watkins-matt/home-assistant-google-keep-sync/releases/tag/0.9.8.1. It should now be safe to update to Home Assistant 2024.6.1.

For anyone wondering, the source of this issue was actually in the requests library. Home Assistant 2024.6.1 updated requests from 2.31.0 to 2.32.3 (https://github.com/home-assistant/core/pull/118868). The relevant issue in the requests library can be found here: https://github.com/psf/requests/issues/6730.
